### ISSUE TITLE
Create a page for admin to cancel the matches and re-run

### ISSUE THREAD

**Issue by chiang831** [chiang831/elo-rating-site#1]
Now that we have better data structures, we can re-run the match results easily.
P1: Add a page to re-run the match results and update rating in them.
P2: Add a page for admin to select some matches to be removed. This is P2 because admin can always use console from app engine.

**Comment by music960633** [comment]
Done in 44bb5b3 and 546dfaa

**Comment by chiang831** [comment]
Awesome!!
