### ISSUE TITLE
Tetrominoes.ttf should be cached

### ISSUE THREAD

**Issue by music960633** [chiang831/elo-rating-site#3]
Loading Tetrominoes.ttf can take more than two seconds, which is a long time.
I tried to add
```
- url: static/
  static_dir: static
  expiration: "0d 10m"
```
in *app.yaml* to cache static files. It works when using dev_appserver, but gets 404 after deploying on real server.

**Comment by chiang831** [comment]
Here the default cache expiration time is already 10 minutes

https://cloud.google.com/appengine/docs/standard/python/config/appref#default_expiration

**Comment by chiang831** [comment]
Oh...I think we should not cache whole static/ directory.
If we cache 10 minutes, we need to wait for 10 minutes for the browser to get the new html / js files.
It is weird that what we did not see this before.
Maybe cache does not work, or, not work as I thought.

**Comment by chiang831** [comment]
On my desktop it takes 220 ms to load the font XD

**Comment by chiang831** [comment]
Tested again. The time to load ttf is about 200 ms. It should be okay.
